name: account_book
description: App project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: 3.0.7
  intl: 0.17.0
  drift: 2.8.2
  sqlite3_flutter_libs: 0.5.10
  path_provider: 2.0.11
  path: 1.8.3
  get_it: 7.2.0
  dio: 4.0.6
  provider: 6.0.3
  uuid: 3.0.6
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 5.13.0

  drift_dev: 2.8.3
  build_runner: 2.4.5
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true